# Generated by Django 5.2 on 2025-04-12 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 12, 10, 41, 50, 569844), null=True),
        ),
    ]
